modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://go.ftb.team/support-mod-issues"
license = "All Rights Reserved"

[[mods]]
modId = "ftbultimine"
version = "${version}"
displayName = "FTB Ultimine"
authors = "FTB Team"
description = '''
Allows you to break multiple blocks at once
'''

[[dependencies.ftbultimine]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbultimine]]
modId = "minecraft"
mandatory = true
versionRange = "[${mcversion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbultimine]]
modId = "architectury"
mandatory = true
versionRange = "[${archversion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbultimine]]
modId = "ftblibrary"
mandatory = true
versionRange = "[${ftblibraryversion},)"
ordering = "NONE"
side = "BOTH"

