modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/FTBTeam/FTB-Ultimine/issues"
license = "All Rights Reserved"

[[mods]]
modId = "ftbultimine"
version = "${file.jarVersion}"
displayName = "FTB Ultimine"
authors = "LatvianModder"
description = '''
Allows you to break multiple blocks at once
'''

[[dependencies.ftbultimine]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ftbultimine]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"