modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/FTBTeam/FTB-Ultimine/issues"

[[mods]]
modId="ftbultimine"
version="${file.jarVersion}"
displayName="FTB Ultimine"
authors="LatvianModder"
description='''
Allows you to break multiple blocks at once
'''

[[dependencies.ftbultimine]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ftbultimine]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,)"
    ordering="NONE"
    side="BOTH"