modLoader = "javafml"
loaderVersion = "[${neoforgeloaderversion},)"
issueTrackerURL = "https://go.ftb.team/support-mod-issues"
license = "All Rights Reserved"

[[mixins]]
config = "ftbultimine-common.mixins.json"

[[mods]]
modId = "ftbultimine"
version = "${version}"
displayName = "FTB Ultimine"
authors = "FTB Team"
description = '''
Allows you to break multiple blocks at once
'''

[[dependencies.ftbultimine]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforgeversion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbultimine]]
modId = "minecraft"
type = "required"
versionRange = "[${mcversion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbultimine]]
modId = "architectury"
type = "required"
versionRange = "[${archversion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbultimine]]
modId = "ftblibrary"
type = "required"
versionRange = "[${ftblibraryversion},)"
ordering = "NONE"
side = "BOTH"

